name: merge depenendecy update PRs
branding:
  icon: git-merge
  color: green
description: automatically merge dependency update PRs
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token used to perform the merge'
    required: true
  ALLOWED_UPDATE:
    default: patch
    description: 'the type of update to automatically merge. allowed values: "patch", "minor", "major"'
  MERGE_METHOD:
    default: merge
    description: 'the merge method to use. allowed values: "merge", "squash", "rebase"'
runs:
  using: docker
  image: Dockerfile